# Copyright (c) 2026 PEKKAMC
# All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

from enum import StrEnum


class Color(StrEnum):
    # BASE COLORS
    WHITE = "#FFFFFF"
    BLACK = "#000000"
    TRANSPARENT = "transparent"

    # UI BACKGROUNDS
    CARD_BACKGROUND = "#FFFFFF"
    COMPLETED_BACKGROUND = "#E0E0E0"
    DIALOG_BACKGROUND = "#F8FAFC"
    AGGREGATE_BACKGROUND = "#F0F5EE"
    ON_TRACK_BACKGROUND = "#145C26"
    ACTIVITY_BACKGROUND = "#F3F5F1"
    MENU_BACKGROUND = "#263238"
    DEFAULT_CONTAINER_BACKGROUND = "#ECEFF1"

    # BORDERS & SHADOWS
    INPUT_BORDER = "#E0E0E0"
    DEFAULT_BORDER = "#BDBDBD"
    COMPLETED_BORDER = "#9E9E9E"
    SHADOW = "#1A000000"

    # TEXT COLORS
    PRIMARY_TEXT = "#212121"
    SECONDARY_TEXT = "#757575"
    SUBTITLE_TEXT = "#9E9E9E"
    BODY_TEXT = "#424242"
    COMPLETED_TEXT = "#616161"
    AGGREGATE_TEXT = "#5A7A5D"
    BLAND_TEXT = "#9E9E9E"
    DEFAULT_TEXT = "#263238"
    ERROR_TEXT = "#FFEB3B"

    # ACTIONS & BUTTONS
    PRIMARY_ACTION = "#1D7333"
    NEGATIVE_ACTION = "#D32F2F"
    COMPLETED_ACTION = "#1976D2"
    DELETE_ACTION = "#E53935"
    DARK_BUTTON = "#1E293B"
    CONFIRM_BUTTON = "#004D40"
    DEFAULT_BUTTON = "#263238"

    # PROGRESS BARS
    PROGRESS_ACTIVE = "#2E7D32"
    PROGRESS_COMPLETED = "#42A5F5"
    PROGRESS_BACKGROUND = "#DCEDC8"

    # ICONS
    MENU_ICON = "#008800"

    # LOGIN PAGE
    USER_TILE_BACKGROUND = "#F5F5F5"

    # HOME PAGE
    CHART_INCOME = "#4CAF50"
    CHART_INACTIVE = "#EEEEEE"
    CHART_EXPENSE = "#F44336"