# Copyright (c) 2026 PEKKAMC
# All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

from enum import StrEnum


class Color(StrEnum):
    # BASE COLORS
    WHITE = "#FFFFFF"
    BLACK = "#000000"
    TRANSPARENT = "transparent"

    # UI BACKGROUNDS
    PAGE_BACKGROUND = "#F7FAF8"
    NAVIGATION_BACKGROUND = "#FFFFFF"
    CARD_BACKGROUND = "#FFFFFF"
    COMPLETED_BACKGROUND = "#E0E0E0"
    DIALOG_BACKGROUND = "#F8FAFC"
    AGGREGATE_BACKGROUND = "#F0F5EE"
    ON_TRACK_BACKGROUND = "#145C26"
    ACTIVITY_BACKGROUND = "#F3F5F1"
    MENU_BACKGROUND = "#FFFFFF"
    DEFAULT_CONTAINER_BACKGROUND = "#ECEFF1"

    # BORDERS & SHADOWS
    INPUT_BORDER = "#E0E0E0"
    DEFAULT_BORDER = "#BDBDBD"
    COMPLETED_BORDER = "#9E9E9E"
    SHADOW = "#16000000"

    # TEXT COLORS
    PRIMARY_TEXT = "#212121"
    SECONDARY_TEXT = "#757575"
    SUBTITLE_TEXT = "#9E9E9E"
    BODY_TEXT = "#424242"
    COMPLETED_TEXT = "#616161"
    AGGREGATE_TEXT = "#5A7A5D"
    BLAND_TEXT = "#9E9E9E"
    DEFAULT_TEXT = "#263238"
    ERROR_TEXT = "#FFEB3B"

    # ACTIONS & BUTTONS
    PRIMARY_ACTION = "#1D7333"
    NEGATIVE_ACTION = "#D32F2F"
    COMPLETED_ACTION = "#1976D2"
    DELETE_ACTION = "#E53935"
    DARK_BUTTON = "#1E293B"
    CONFIRM_BUTTON = "#004D40"
    DEFAULT_BUTTON = "#263238"

    # PROGRESS BARS
    PROGRESS_ACTIVE = "#2E7D32"
    PROGRESS_COMPLETED = "#42A5F5"
    PROGRESS_BACKGROUND = "#DCEDC8"

    # ICONS
    MENU_ICON = "#008800"

    # LOGIN PAGE
    USER_TILE_BACKGROUND = "#F5F5F5"

    # HOME PAGE
    CHART_INCOME = "#4CAF50"
    CHART_INACTIVE = "#EEEEEE"
    CHART_EXPENSE = "#F44336"

    DARK_SURFACE = "#0B2B26"
    PRIMARY = "#1A4734"
    LIGHT_ACCENT = "#DAF1DE"

    EXPENSE_ACTION_BACKGROUND = "#E90C00"
    EXPENSE_LABEL_TEXT = "#FFC1C1"
    EXPENSE_VALUE_TEXT = "#FF8A8A"

    SAVINGS_LABEL_TEXT = "#FFE082"
    SAVINGS_VALUE_TEXT = "#FFD54F"

    LESSON_BANNER_BACKGROUND = "#0F172A"
    LESSON_ICON_BACKGROUND = "#DBEAFE"
    LESSON_ICON_COLOR = "#1E40AF"

    GOAL_ITEM_BACKGROUND = "#FAF5E8"
    GOAL_ITEM_BORDER = "#F3EFE0"

    PROGRESS_TRACK_BACKGROUND = "#E2E8F0"
    GOAL_HEADER_ICON_BACKGROUND = "#FEF3C7"
    GOAL_HEADER_ICON_COLOR = "#92400E"
    CARD_DIVIDER = "#F1F5F9"

    METRIC_PILL_BACKGROUND = "#14FFFFFF"
    METRIC_PILL_BORDER = "#1FFFFFFF"
    SCAN_BUTTON_BORDER = "#33FFFFFF"

    AI_ADVICE_BACKGROUND = "#E60B2B26"
    AI_ADVICE_BORDER = "#4D10B981"